use_frameworks!

platform :ios, '8.0'

workspace 'BaiduMapSDK.xcworkspace'

#target 'BaiduMapSDK_Example' do
#  pod 'BaiduMapSDK', :path => '../'
#
#  target 'BaiduMapSDK_Tests' do
#    inherit! :search_paths
#
#
#  end
#end

#pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
#  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
#end


#post_install do |installer|
#  project = installer.pods_project
#
#  # prevent frameworks which they are already linked with a module from being linked with the main target again
#  installer.aggregate_targets.each do |target|
#    project.build_configurations.each do |build_configuration|
#      configFilePath = target.xcconfig_path(build_configuration.name)
#      configFile = File.read(configFilePath)
#      configFile = configFile.gsub(/-framework "BaiduMapAPI_Base" /, '')
#      configFile = configFile.gsub(/-framework "BaiduMapAPI_Cloud" /, '')
#      configFile = configFile.gsub(/-framework "BaiduMapAPI_Map" /, '')
#      configFile = configFile.gsub(/-framework "BaiduMapAPI_Search" /, '')
#      configFile = configFile.gsub(/-framework "BaiduMapAPI_Utils" /, '')
#      configFile = configFile.gsub(/-framework "BaiduMapAPI_Utils" /, '')
#      File.open(configFilePath, 'w') { |file| file << configFile }
#    end
#  end
#end
